### ISSUE TITLE
RGB TIFF Support

### ISSUE THREAD

**Issue by eaholman** [bluesky/tiled#133]
Tried to use Tiled to access an RGB dataset of colored TIFF images and received the following error--
Traceback (most recent call last):
tiled.client.utils.ClientError: 400: Block index out of range

**Comment by danielballan** [comment]
Hello @eaholman. Thanks for the report. Could you upload an example TIFF image? TIFF is a highly varied format, so it would be useful to be able to test against some specific TIFFs of interest to you.

**Comment by eaholman** [comment]
I am unable to upload here since TIFF is not supported by Github Issues. May I directly email you an image extracted from the image stack?

**Comment by eaholman** [comment]
I have emailed the TIFF to you with the Issue number in the title.

**Comment by dylanmcreynolds** [comment]
For what it's worth, I recently tried accessing a TIFF stack (multiple images in the same tiff file) and received the same error. I think an example file has been provided over email.

**Comment by danielballan** [comment]
Circling back to confirm that I received the email. I will work on this shortly.

**Comment by danielballan** [comment]
#143 included a unit test that constructs and tests against a TIFF with the same dimensionality and data type as the provided sample.

Would you confirm whether this branch works in your application, @eaholman?

**Comment by eaholman** [comment]
I verified that this branch works with our TIFF files to read without throwing an error.

**Comment by danielballan** [comment]
Thanks @eaholman!
