### ISSUE TITLE
Docs: turn on logging

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#134]
Would be nice to add to the documentation (aybe in a how-to?) instructions for turning on the client logging of server perforamnce:

```
from tiled.client.utils import logger
logger.setLevel("DEBUG")
```

**Comment by danielballan** [comment]
This can be short. I guess it should cover:

* How to turn on
* What the abbreviated items standard for and mean
* The time units (ms)
* A link to the MDN page on the Server-Timing standard
* How to turn off
