### ISSUE TITLE
Enable Adapters to support search by path parameter as equivalent to search by query parameter.

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#158]
## Motivation

From the beginning, we have received a trickle of feedback that URLs for things as a simple as "the last scan" or "all the scans for this proposal" are pretty busy-looking and not memorable. Behind a Python client, this isn't so important, but for some usages it makes a difference.

As an example, URLs like

```
/node/search/csx?filter[proposal][id]=12345
/node/search/csx?sort=-time&page[limit]=3
```

are less memorable than URLs like

```
/node/search/csx/proposal/12345
/node/search/csx/latest/3
```

At the end of the day, whether a search parameter is given as a path parameter or a query parameter is somewhat arbitrary. For important searches that are parameterized by a single value, this could be a convenient alias.

Notice that this is **_not_ equivalent to soft-links** because it only affects `/node/search` not `/node/metadata`. A soft-link would mean that

```
/node/metadata/csx/proposal/12345/{run_uid}
```

would be an aliases for

```
/node/metadata/csx/uid/{run_uid}
```

But that is not what we propose to do. We propose to leave the `/node/metadata` route alone, and to extend the behavior of `/node/search` only. The items in the response from

```
/node/metadata/csx/proposal/12345/
```

would include `self` links that point to

```
/node/metadata/csx/uid/{run_uid}
```

In this way, each item in the tree only has one location. The new `/node/search` routes are just listings. This has important implications for things like caches.

In the future, when we support writing from the client, we might likewise support something like:

```
/node/submit/csx/proposal/12345
```

where `/proposal/12345` is interpreted as metadata, equivalent to `{"proposal": 12345}` in the JSON payload. And of course any conflict with the JSON payload would be an error, likely a `400 Bad Request`.

We could decide to support this only for searching but not for writing. Doing the opposite, however, would not make sense.

Filters that use path parameters instead of query parameters, in addition to being more readable, may enable external caches and load balancers to do more optimization because they can see from the path segments what you are trying to access and know more about whether you are allowed to see it.

### Python client

Currently, the Python client assumes that a search result named `c` that was returned by a search on `/node/search/a/b` must be located at `/node/search/a/b/c`, a subpath of the path being searched. This proposal would break that assumption, because `/node/search/csx/proposal/12345` would include results whose location is `/node/metadata/csx/uid/{run_uid}` To deal with this, the client should just rely on the results' `self` links, which will always be correct, rather than manually munging paths. This is simpler anyway and, IMO, a change we should make to the client in any case.

### Server

On the server side, when traversing the path, we currently do:

```py
node = root_tree
for segment in path:   # ("a", "b", "c") for the URL /node/search/a/b/c
    node = node[segment]
```

We would add an optional method named something like `path_parameter_queries()` to Adapters, like this:

```py
>>> adapter.path_parameter_queries()
PathParameterQueries(mount_at="uid", queries={"proposal": filter_by_proposal, "cycle": filter_by_cycle, "latest", filter_latest_N})
```

and incorporate it in the loop above such that we end up "mounting" the adapter's normal contents at a subpath (`uid`) and treating other special subpaths as searches. The point of "mounting" is to add a level of nesting such that the searches (`proposal`, `cycle`, `latest`) do not share a namespace with `{run_uid}`.

```
# All results, same as now but "mounted" at a subpath named /uid in this case
/node/search/csx/uid

# Filtered results
/node/search/csx/proposal/12345
```

The results of these path-parameter-queries could include, in the `links` section, the URL to an equivalent search using query parameters, like `/node/search/csx/uid?filter[proposal][id]=12345`.

**Comment by danielballan** [comment]
I intended to tag @tacaswell for talking this through with me for an hour today. Thanks, Tom!

**Comment by dylanmcreynolds** [comment]
This is very useful and creates clean paths, but I am concerned that this causes paths to be doing too much. URLs already have a standard place for query parameters `?`, with a natural delimiter for separating keys and values `&`. That feels pretty ergonomic to me. This proposal means that you have to know that search path segments come in sets of two.

I don't think this is supported now, but let's say I want to support searching for `name=zaphod` in a tree at `/ab/c` level rather than the root level. How is the server going to know where path segments end and search terms begin? `/a/b/c/name/zaphod`

**Comment by danielballan** [comment]
I’ve come around to agreeing that this idea muddies filtering and tree traversal too much. Clients can experiment with providing a view of “filtering as tree traversal” without any changes in core.
