### ISSUE TITLE
Handle nested dicts metadata in HDF5 encoder.

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#169]
When `node.metadata` contains a nested dict like `{"a": {"b": 1}}` this will fail

https://github.com/bluesky/tiled/blob/5512e9914165dc5a83290f707734204716479899/tiled/structures/node.py#L52

because HDF5 does not support nested metadata.

## Possible solutions

1. Fail if the user attempts to export a node with nested metadata as HDF5, just as we fail when a user tries to export a 5-dimensional array as a PNG. Xarray does this for netCDF (an HDF5 layout):

```py
In [4]: ds = xarray.Dataset({}, attrs={"a": {"b": 1}})

In [5]: ds.to_netcdf("test.h5")
...
TypeError: Invalid value for attr 'a': {'b': 1}. For serialization to netCDF files, its value must be of one of the following types: str, Number, ndarray, number, list, tuple
```

2. Choose a delimiter like `.` and then flatten `{"a", {"b": 1}}` into `{"a.b": 1}`. This opens the possibility of delimiter collision (What happens when we are given `{"a": {b": 1}, "a.b": 2}`. I think it is probably OK to just fail in that case.

3. Silently drop whatever metadata that we cannot encode. On the one hand, we already silently drop `node.metadata` when we encode arrays as `text/csv` or `image/png`. On the other hand, this would be different because the metadata would _sometimes_ be included and sometimes not, and this might be very unexpected and mysterious to the user. That could be really frustrating behavior, so I think we should rule this option out.

4. Add query parameter to the HTTP API to let the user switch between the options 1-3 above. Python itself takes the same approach with [`str.encode`](https://docs.python.org/3/library/stdtypes.html#str.encode) where unencode-able data can raise an error (1), be replaced (kind of like 2), or ignored (3). I'm reluctant to add more complexity to the API but I think this may be an "irreducible complexity" that we won't be able to avoid forever.

**Comment by ksunden** [comment]
In the past with similar issues I've opted to warn, but not error out. Though that choice is largely because the things I'm leaving out are not important to me (and that much may not generalize) but I still wanted to be aware that they were being ignored. Not sure how warnings would translate over the http api, though.

**Comment by danielballan** [comment]
Yeah, I’ve wondered this in other contexts in Tiled where it was tempting to use warnings. We could easily enough add a “warnings” key to the HTTP response body, containing a list of strings, and teach the Tiled Python client to issue any items in that list as warnings.

But one of our design goals is to work well with genetic HTTP clients that don’t know anything about Tiled. Someone using a generic client like curl or a web browser would get any warnings and, likely enough, may never read deep enough into our docs to know where to check for them. I think “fail with an error message that explains how to ignore the failure and get a partial result” may be more discoverable.

**Comment by kleinhenz** [comment]
Another option is to put the metadata into a special group (`_metadata`?) instead of using attributes.

**Comment by prjemian** [comment]
You're making a new schema and likely have crossed the theshhold to justify supporting output to an existing HDF5 schema.  Of those, I know of NeXus and DataExchange in our community.

**Comment by danielballan** [comment]
This is a good point, @prjemian. If you have a dataset with nested metadata, we could assert that raw HDF5 does not fit your requirements. You need to fix your adapter to encode HDF5-compatible metadata or you need to adopt a format (which may be a layout of HDF5) that places your metadata in an encodable structure.

**Comment by danielballan** [comment]
Revisiting this: I think we can leverage `specs` to be flexible about how we handle this. The generic behavior should be, I think, to raise a clear error—option (1) above. But we can register custom HDF5 exporters for certain specs (like `BlueskyRun`) that do something more useful. For BlueskyRun, we can take option (2) taking advantage of our knowledge that keys in BlueskyRun metadata will never have dots.
