### ISSUE TITLE
Explore other ways to identify file types

### ISSUE THREAD

**Issue by prjemian** [bluesky/tiled#175]
When serving a directory of files, there may exist valid data files that lack a feature in the file name (such as a file extension) to identify the type of file.  For example, there is no common file extension for SPEC data files and some users are accustomed to omitting a file extension.  As shown in #174, the file extension may be too complicated to examine or not one of the recognized values.  The `.dat` and `.txt` extensions are also used for various types of data files, including CSV.

Need some programmatic technique to identify the type of file, similar to the UNIX [`file`](https://linuxhandbook.com/file-command/) command.  Python examples include [`is_spec_file(filename)`](https://spec2nexus.readthedocs.io/en/latest/spec.html?highlight=is_spec_file#spec2nexus.spec.is_spec_file), [`isNeXusFile(filename)`](https://github.com/prjemian/punx/blob/75477ab63518d8c134ebc02bf839c60042a0461e/punx/utils.py#L112)

Such routines could be called with unrecognized files.

**Comment by prjemian** [comment]
The addition technique could be inserted into this block: https://github.com/bluesky/tiled/blob/3d269d444311b217af9925b935fdd7ab3773a56c/tiled/adapters/files.py#L648-L654

Might be better to search known mimetypes _first_ since identification by file content is the more expensive operation.  Associate each identified file type with _ad hoc_, unique mimetype.

**Comment by prjemian** [comment]
That seems very general.  I like it.

**Comment by danielballan** [comment]
@prjemian This is now implemented in v0.1.0a67 and documented at https://blueskyproject.io/tiled/how-to/read-custom-formats.html. 

Let me know if you get a chance to try it out on SPEC or NeXus.

**Comment by prjemian** [comment]
Starting to look at this now.  [Case 2](https://blueskyproject.io/tiled/how-to/read-custom-formats.html#case-2-no-file-extension) is the most likely scenario since our data files may have extensions.   Yet that extension cannot be trusted to be informative when the extension content is overloaded for various data formats (such as `.dat`: could be SPEC, CSV, binary, ..., `.h5` could be NeXus, Data Exchange, or other).

The interface is called for each file:

```py
# custom.py

def detect_mimetype(filepath, mimetype):
    if mimetype is None:
        # If we are here, detection based on file extension came up empty.
        ...
        mimetype = "text/csv"
    return mimetype
```

While this could become time-expensive when repeating over a directory structure with many similar files (a typical pattern), it could be optimized.  One optimization (in the custom handler) could be a sense of recognition that files in a directory likely follow a pattern, such as any combination of these rules:

- all files _in this directory_ are [this known format], regardless of naming style
- NeXus/HDF5 area detector files _in this directory_ have `.h5` extension
- SPEC files _in this directory_ have `.dat` extension
- custom NeXus/HDF5 files _in this directory_ have `.hdf5` or `'nx`' or 'nxs` extension
- file _starts_ with recognized pattern

Even if that handling is better suited to a class, the optimizing class would be called from the `detect_mimetype()` function.  Seems straightforward.

**Comment by prjemian** [comment]
Another optimization:

- directory contains a file that provides the mime type mapping
 - the mapping file could be created manually or by a previous run

**Comment by danielballan** [comment]
This aligns with two optimizations I have been working on:

* Stash the detection results (and metadata) in an index file so that the detection only has to happen once, not on every tiled server startup.
* Enable the user to explicitly index (or would a better term be “register”) certain files or directories with a new command like `tiled register`. This would give the user the opportunity to provide additional guidance on how to handle those specific files or directories, perhaps `tiled register dir/ --ext .h5=application/x-nexus`. That may be easier for users than going through trial-and-error to guide an automated detection scheme.

**Comment by prjemian** [comment]
The local mapping may provide more flexibility.  Our directories tend to have mixed content such that an `ignore` setting would be good for Python, SPEC macro, MatLab procedures, IgorPro procedures, text, markdown, ...  But then, this is just another aspect of a custom handler.

Unless you have some specifics in mind, let's work up some custom handlers and compare.

**Comment by danielballan** [comment]
Sounds good, let’s!
