### ISSUE TITLE
Investigate connection to n5

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#193]
This might be useful for writeable array storage. https://github.com/saalfeldlab/n5

**Comment by dylanmcreynolds** [comment]
Interesting. Is this used somewhere that we know of? Last update was a year ago.

**Comment by danielballan** [comment]
Ah, not a good sign.

It was brought to my attention at a conference (must have been more than two years ago) and I dashed off this Issue to capture the idea from personal notes.

**Comment by danielballan** [comment]
It looks like the last update was actually in February. I'm not sure whether this is really applicable/interesting, but I'll leave this open for awhile as a reminder that it might be.

**Comment by danielballan** [comment]
I'll go ahead and close this. Seems likely Zarr will be a good target for array storage.
