### ISSUE TITLE
Add API keys that can only access certain data.

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#228]
## Use Case

A scientist wants to generate URL(s) to internal data to share data conveniently with collaborators. The URL must contain an API key so that it can be pasted into a simple web client and get access. There may be multiple URLs to different data, all sharing the same API key. Consider for example pasting links into ImageJ or Igor Pro, or any web client that cannot go through the OAuth2-style login exchange. You can't "login"; you need an API key that you can stick into a URL.

Currently, if the scientist generates an API key [as instructed by our documentation](https://blueskyproject.io/tiled/how-to/api-keys.html) and shares it, there are two problems:

* The collaborators will be able to access _everything_ the scientist can access, which is likely more than the scientist intends to share.
* If the scientist loses access or deletes their account when they leave or retire, the rest of the team will lose access. This probably is not what is intended.

## Proposal

The API keys that we currently support are similar to [GitHub Personal Access Tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). They are associated with a "Principal" (i.e. a person) and list of scopes (e.g. read, write). The scopes can restrict _what_ the API key can be used for (e.g. read-only) but not _which_ things they can access.

We propose to add a second kind of API key, more similar to [GitHub Deploy Keys](https://docs.github.com/en/developers/overview/managing-deploy-keys). These would be associated with a "filter" to narrow _which_ data can be accessed. It could narrow the access to, for example, one beamline or one proposal or some other search criteria. It would not retain any association with the person (Principal) who created it. As long as the person who creates the key has access to the relevant data at the moment when they create key, it won't matter if that Principal later loses access or is deleted. The key, which we might call a "Shared Key", is for teams to share access to specific resources. Shared Keys can be revoked by anyone with access.

This seems to make the concept of "service accounts" superfluous. We have laid a little track for them, but there is no API for creating one, and none have been created as far as I know. (You would have to do it in SQL directly.) I think that if we accept this proposal, we may later decide that we never need service accounts. Perhaps our requirements can be met with Shared Keys because Shared Keys, once created, are not associated with a Principal.

## Implementation

The schema for the API keys we have _now_ is:

```py
class APIKey(Timestamped, Base):
    __tablename__ = "api_keys"

    first_eight = Column(Unicode(8), primary_key=True, index=True, nullable=False)
    hashed_secret = Column(
        LargeBinary(32), primary_key=True, index=True, nullable=False
    )
    expiration_time = Column(DateTime(timezone=False), nullable=True)
    latest_activity = Column(DateTime(timezone=False), nullable=True)
    note = Column(Unicode(1023), nullable=True)
    principal_id = Column(Integer, ForeignKey("principals.id"), nullable=False)
    scopes = Column(JSONList(511), nullable=False)

    principal = relationship("Principal", back_populates="api_keys")
```

It has an optional expiration time and a list of scopes that can be used to restrict _what_ it can do (e.g. read-only). The `principal` is used, in conjunction with an `AccessControlPolicy`, to determine at access time _which_ data the key can be used to access.

(We might want to rename the table `APIKey` to `PersonalKey` to avoid ambiguity.)

The schema for this new, second kind might look like the sketch below. Like the original `APIKey`/`PersonalKey` it has an expiration time and a list of scopes. But it replaces `principal` with `path` and `filter` to control _which_ data it can access.

```py
class SharedKey(Timestamped, Base):
    __tablename__ = "api_keys"

    first_eight = Column(Unicode(8), primary_key=True, index=True, nullable=False)
    hashed_secret = Column(
        LargeBinary(32), primary_key=True, index=True, nullable=False
    )
    expiration_time = Column(DateTime(timezone=False), nullable=True)
    latest_activity = Column(DateTime(timezone=False), nullable=True)
    note = Column(Unicode(1023), nullable=True)
    scopes = Column(JSONList(511), nullable=False)
    path = Column(JSONList, nullable=False)
    filter = Column(JSONDict, nullable=False)
```

The `path` navigates us to a node and the `filter` applies a query to that node. Only search results for that filter on that node are allowed to be accessed using this key.

Examples:

```
path=["csx"]  filter={}  # all of CSX beamline
path=["csx"]  filter={"data_session": "pass-12345"}  # only a certain proposal
path=["csx"]  fitler={"purpose": "calibration"}  # only a certain type of measurement
```

Notice that the filter is not an open-ended search. It is specifically an equality check. It cannot be used to apply complex filters like "atomic number < 30". This keeps things simple and avoids typing it to a specific database or query language.

That formulation plays well with @kleinhenz's work on the duality of paths and certain queries in Tiled, without immediately fully committing to it. If we someday buy all the way into that, then `path` and `filter` become equivalent representations---`["element", "Ni"]` and `{"element": "Ni"}`---and we could go so far as deprecating `path`. I can't rush that decision into NSLS-II's deployment, but we can leave space for the possibility.

**Comment by dylanmcreynolds** [comment]
I like this formulation, and the use case is clearly stated. A couple of points:/

- Can the filter be nullable? Can you not create a ShareToken based entirely on a path?
- Can the path be nullable? Can you not create a ShareToken based entirely on filters?
- Can filter keys have some hierarchy? Say my nodes have some metadata with a structure, can I say something like:
```path=["csx"]  fitler={"scan.purpose": "calibration"}  # only a certain type of measurement```
or is this too much?

**Comment by danielballan** [comment]
Conceptually I think both must be nullable. I think it’s an implementation question whether “null” should just be `[]` and `{}` respectively or actually null.

Yes, I think we must support nested keys in the filters. At least to start, I think we can use dot as a separator (like MongoDB). We could always move to list-of-strings to represent nested keys if dot becomes ambiguous.

**Comment by stuartcampbell** [comment]
Just a comment regarding service accounts and them being not required anymore.  I think we would probably have some accounts, but they would change from themselves being the 'vehicle' to get permissions to a given level of access, but now would probably be more of a practical conduit to provide and use a 'deployment key'. They then might just need to be more like a traditional local daemon/service account rather than a global service account.

**Comment by danielballan** [comment]
That makes sense.

It occurred to me sometime after I wrote the original post that GitHub has a notion of service ("bot") accounts even though it also has Deploy Keys, and that we would probably need both as well. So I will not rush to remove any of the track we have laid for service accounts.

**Comment by danielballan** [comment]
_Personal Note: I sprained my ankle on Friday being chased by 5 neighborhood children in wet grass (no regrets!) so I am alone in the house and thinking about shared keys._

When a user wants to make a new SharedKey we’ll have to consult the AccessControlPolicy to ask which nodes that Principal is allowed to share (presumably less than or equal to the nodes they are allowed to read). Then we’ll take the intersection of that with any additional filters the user wants to apply to this specific key, potentially further restricting which data it can access.

This filter, then, is inserted into the SQL table SharedKeys. As I argued above, it should be a simple query specification that does not tie us to MongoDB or any backend. (If we put literal MongoDB queries in our database it will be very hard to evolve our schema or change technologies!)

Currently, each AccessControlPolicy implementation  is tightly coupled to a specific database backend. For example, we filter_results by applying a MongoDB query. This tight coupling and deep access is both brittle and a little worrying to me. Perhaps, instead, the ACP should only interact with the backend through that same simple query specification:

```python 
class ACP:
    def permissions(self, principal):
        …
        return {
            "read": {"data_sessions": […], "experiment_type": "…"},
            "share": {"data_sessions": […], "experiment_type": "…"},
             "write": NO_ACCESS,
        }
```

where you may interpret the inner dicts as filters that happen to look like simple Mongo queries—but only simple ones like these are allowed, and Tiled adapters translate them to actual queries for their backend, whether Mongo or otherwise.

The empty filter `{}` means “everything in this node” and the sentinel `NO_ACCESS` clearly means no access.

This language is very internal—just between the Adapter and the ACP—so we can make it richer in the future if needed. (Perhaps we want a concept of logical NOT, for example.) Indeed the language inside is opaque to the tiled server which is why @kleinhenz was able to make something custom between his Adapter and his ACP without upstream changes. But when we introduce Shared Keys and begin _persisting_ this syntax in database rows, we need some care to ensure forward-compatibility of those filters.

The keys like "read" could be actual scopes like "read:metadata" and "read:data" if we would rather. I suspect that high level meta-scopes like plain "read" will be sufficient and easier. Individual API keys’ scopes may restrict the scopes further; the ACP is just telling us the maximum scope this Principal has in this Node, and on which children.

I like that this enables a user with restricted access within a node (e.g. to a couple proposals) to make shared keys for their collaborators’ applications which have the same access they do, or less.

I like that this enables an administrator to selectively control which data a user can read separately from what they can share, even if in many cases those may be the same.

**Comment by danielballan** [comment]
After examining this question for awhile in various conversations, I believe the consensus is that Service Accounts actually meet all our requirements and creating "Deploy Key"-style tokens for arbitrary nodes would be too hard to review and manage.
