### ISSUE TITLE
Wildcard for mimetypes_by_file_ext?

### ISSUE THREAD

**Issue by J-avery32** [bluesky/tiled#255]
I am trying to create a config.yml for a specialized format as instructed here: https://blueskyproject.io/tiled/explanations/specialized-formats.html

However, in this format files of the same type have a variety of different extensions simply because the '.' character is used in these files for another kind of information, not an actual extension. 

For example some of my files look like this:

polymer_10_new_Ck150V.2050
polymer_10_new_Ck150V.3050
polymer_10_new_Ck150V.4050

but they are all the same data format.

Additionally, there are two files in this directory that have the extension ".log"

I would like to create an adapter for the .log files and then a separate adapter for all the rest.

Are there any wildcards that I can use in the yaml field `mimetypes_by_file_ext`?

**Comment by danielballan** [comment]
I think that the proposal in https://github.com/bluesky/tiled/issues/175#issuecomment-1045192375 (not yet implemented) would address this. I'll implement it soon and ask you to give it a try if you don't mind.
