### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by gwbischof** [bluesky/tiled#263]
We are getting this error at rsoxs on some scans.  The scan we have been testing is 42934.
We think scans that are bigger than 500MB are giving us this error.
I think we can improve this error message if it is indeed a size limit error.

```
136  ->	        processed_uid = tiled_client_processed.write_array(
137  	            subtracted.data,
138  	            metadata={
139  	                "field": field,
140  	                "python_environment": sys.prefix,
141  	                "raw_uid": full_uid,
142  	                "operation": "dark subtraction",
143  	            },
144  	        )
```

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> /nsls2/data/sst/rsoxs/shared/workflows/export.py(136)write_dark_subtraction()
```

**Comment by danielballan** [comment]
When the error comes from FastAPI, it is JSON-formatted and we get a nice error. When the error comes from something in between, such as nginx or some BNL proxy, it may not be JSON. (It is like HTML.) The client's attempt to parse it as JSON fails, and we end up here.

Next steps to solve the error-reporting issue here:

1. Reproduce this interactively.
2. Verify that the exception happens [when we try to decode the response as JSON but it's not JSON](https://github.com/bluesky/tiled/blob/c6ef656555694d337bbdfcdad9491ce07b867f02/tiled/client/utils.py#L32).
3. Place `response.json()` in a try/except and provide a better failure mode.

Then, to address this specific problem (uploading more than 500 MB) we need to add chunked upload and storage. This is a multi-step process, but I've been thinking about how best to do it for awhile, so I think I can cobble something together quickly to un-block RSoXS. That will involve a minor change to Tiled (add `POST /array/block` route) and some additional functionality in the experimental databroker MongoAdapter.

**Comment by lcdesilva** [comment]
I believe we hit the same issue when we got started at RSoXS. If I am not mistaken @danielballan had to raise the limit to 500 MB. PR history should tell us more.

**Comment by danielballan** [comment]
Right. We raised it, temporarily, knowing that the limit is there for a reason and that we are likely to run into other limits (like timeouts) if we raise it too far.

The proper solution is to upload in smaller chunks rather than one big chunk. Changes need to be made to Tiled and Databroker to support that.
