### ISSUE TITLE
API key usage should bypass requirement of client.login()

### ISSUE THREAD

**Issue by matthewcarbone** [bluesky/tiled#299]
@danielballan @kleinhenz It would be really nice to not have to run e.g.

```python
client = from_uri("https://aimm.lbl.gov/api")
client.login()  # <--- this
```

in order to access the private databases when my API key is already set. Any way to do this?

Originally opened here: https://github.com/AI-multimodal/aimmdb/issues/18.

**Comment by danielballan** [comment]
Thanks for the report. Will fix this and other login inconsistencies as part of #296 . Let’s leave this open to be sure we remember to test this case.

**Comment by x94carbone** [comment]
Awesome, thank you, Dan! 👍

**Comment by nmaytan** [comment]
We stumbled across this old issue during some recent work on auth related things. As captured previously, the requested behavior here is exactly how the client works (and is intended to work) now. If `TILED_API_KEY` is set in your envrionment, that key will be used automatically by e.g. `from_uri()` without prompting for login. Closing this (finally!)
