### ISSUE TITLE
Make XAS example more precise

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#31]
We rushed in #22 with a half-baked (but sufficient) example because there is broad interest in registering custom formats. Now let's revisit that example.

The `metadata` was transliterated from the XAS ASCII format. It is a dict with dots in the keys:

https://github.com/bluesky/tiled/blob/3f0087adf03f850618e6812a615ac617c394acbc/tiled/examples/xas.py#L10-L33

Instead, it should be a nested dict like:

```py
{
    "Column": {
        "1": "energy eV",
        "2": "i0",
        ...
    },
    ...
}
```

The data types of the values should also be reviewed and potentially revised. In Tiled, `metadata` may contain `str`, `int`, `float`, and `datetime`.

**Comment by kleinhenz** [comment]
closed by #34
