### ISSUE TITLE
Documentation: tips on easy startup in docker

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#317]
If you start up without doing anything in authentication config, you get tiled starting up with it's own api_key, like jupyter does. By default gunicorn starts up 4 workers. 

But each worker has its own api_key, making it pretty poor odds that your message will work if you use one of the api_keys on the client auto-generated.

So maybe that [docker page](https://github.com/bluesky/tiled/blob/main/docs/source/how-to/docker.md) could talk briefly about using authentication.allow_anonymous_access or authentication.single_user_api_key for simple configurations. The former is open access, the later per-configures an api_key, so each worker uses the same one.

**Comment by dylanmcreynolds** [comment]
To piggyback on this issue, since it's with the same document. I believe that the uvicorn configuration is extraneous, and maybe a little misleading. 

```yaml
uvicorn:
  host: 0.0.0.0
  port: 8000
```
Since gunicorn is sitting in front, and launches uvicorn workers itself, I think that it does not use a port. (You can see this in the logs, where each work claims to be taking `0.0.0.0:8000`, which would cause port-in-use errors if true. It might be work taking this out of the document, and adding something about making sure that you configure docker (or docker-compose) to expose the gunicorn port.

**Comment by danielballan** [comment]
[This script](https://github.com/bluesky/tiled/blob/main/docker/check_config.py) verified by [these tests](https://github.com/bluesky/tiled/blob/main/docker/test_check_config.sh) is intended to ensure that we never end up with "each worker with its own API key" 

Is it not working as intended?

Agred with the uvicorn comment.

**Comment by dylanmcreynolds** [comment]
I just tried on the command line, and no, it did not work as intended. Each started up with its own key:

```
Using configuration from /deploy/config.yml
Using configuration from /deploy/config.yml
Using configuration from /deploy/config.yml
Using configuration from /deploy/config.yml

    Tiled server is running in "public" mode, permitting open, anonymous access
    for reading. Any data that is not specifically controlled with an access
    policy will be visible to anyone who can connect to this server.


    Navigate a web browser to:

    http://0.0.0.0:8000?api_key=488691f38b12bfc7939c3faaa4acd8fec3547423f2d867d8fc4983d06fc9c118

    or connect a Tiled client to:

    http://0.0.0.0:8000/api?api_key=488691f38b12bfc7939c3faaa4acd8fec3547423f2d867d8fc4983d06fc9c118



    Tiled server is running in "public" mode, permitting open, anonymous access
    for reading. Any data that is not specifically controlled with an access
    policy will be visible to anyone who can connect to this server.


    Navigate a web browser to:

    http://0.0.0.0:8000?api_key=f1740e7cbd22799d4e2a4bfe94dabbd34d98e93017554303e5a28b9a5c0c4f5a

    or connect a Tiled client to:

    http://0.0.0.0:8000/api?api_key=f1740e7cbd22799d4e2a4bfe94dabbd34d98e93017554303e5a28b9a5c0c4f5a



    Tiled server is running in "public" mode, permitting open, anonymous access
    for reading. Any data that is not specifically controlled with an access
    policy will be visible to anyone who can connect to this server.


    Navigate a web browser to:

    http://0.0.0.0:8000?api_key=9ef650abb151c900010553210af5cda989bbe7b4bae16e3b8d433d294d158c8f

    or connect a Tiled client to:

    http://0.0.0.0:8000/api?api_key=9ef650abb151c900010553210af5cda989bbe7b4bae16e3b8d433d294d158c8f



    Tiled server is running in "public" mode, permitting open, anonymous access
    for reading. Any data that is not specifically controlled with an access
    policy will be visible to anyone who can connect to this server.


    Navigate a web browser to:

    http://0.0.0.0:8000?api_key=d745f980e17a75de581003cff4a2b5db2b13160fb2f15396d0bbdbcc2af34f68

    or connect a Tiled client to:

    http://0.0.0.0:8000/api?api_key=d745f980e17a75de581003cff4a2b5db2b13160fb2f15396d0bbdbcc2af34f68

```

**Comment by dylanmcreynolds** [comment]
Another note for this document: the docker command example should reference the image pulled in the instruction above:

```
docker run --rm -p 8000:8000 \
  --mount type=bind,source="$(pwd)/example_files",target=/deploy/example_files \
  --mount type=bind,source="$(pwd)/config.yml",target=/deploy/config.yml \
  --env TILED_CONFIG=/deploy/config.yml  ghcr.io/bluesky/tiled:main
```

**Comment by dylanmcreynolds** [comment]
Added #320 for the non-documentation issues with startup and keys.
