### ISSUE TITLE
Put limits on uploaded metadata

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#328]
Knowing that metadata may be stored in systems that have their own size limits (like MongoDB document size) we should enforce limits on uploaded metadata, including:

- metadata bytesize (10 MB)
- spec character limit (255 characters)
- number of specs per node (20)
- reference label character limit (255) and URL character limit (2047)
- number of references per node (20)

Some of these could be reasonably raised, but it may be best to wait and see if anyone hits them and if so what their use case is.

**Comment by dylanmcreynolds** [comment]
Limiting metadata size to that the (reasonable) limit of a particular persistence tool seems a little random. Woudl you consider a server configuration for that one?

Also, limiting the number of references feels off to me. I'd love to live in a world where each scan was cleanly stored in a single file that could moved around as one bundle, I fear that there are use cases lurking where lots of files are needed. 

I support the rest of these...though I'm dreading the first 2048 character url that someone tries to add.

**Comment by danielballan** [comment]
I think we should ship with a 10 MB (or thereabouts) default for metadata size, but I support making it easily configurable.

I"m not sure if it's clear that by "references" I mean #242---i.e. JSON-LD-ish references---not the number of files/blobs underlying a given Node. I agree that some scans will span, for example, many TIFF files, and we should put no bound on that. Even so, for "references" maybe 20 is a little low. 100? If someone is using 1000 references I worry that's a signal they are misusing the feature. At least, I would want to know more about their use case.

**Comment by danielballan** [comment]
Maybe we should configure `metadata` size limits at the adapter layer. Different storage mechanisms will have different hard upper bounds and different "best practice" upper bounds, so they should be in charge of setting the default value and the allowable range.

Also, "size" depends on serialization method, so it's not something we can enforce cleanly with Pydantic+FastAPI, the way we can set limits of characters in a `spec` string or number of `specs` in the list.
