### ISSUE TITLE
Use "device code flow" to improve terminal-based login

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#341]
External authenticators (e.g. OIDC, SAML) currently require the user to visit a URL in their browser and, after authorizing Tiled, paste a copy back into the terminal. Can we avoid that pasting step? This UX problem of authenticating a smart TV, where the TV tells you to visit a URL on your phone/laptop, login to Amazon or whatever, and enter a short code.

This is apparently called "device code flow", an OAuth2 "extension".

https://www.oauth.com/playground/device-code.html
https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code

## Sketch

The terminal app kicks of the process:

```
-> POST /api/auth/<provider>/authorize
<empty body>
```

The server creates a row in the auth database representing an authentication request in progress, constituting a `session_id`, an `expiration_time`, and a `user_code`, which is a short (~6 character) and short-lived, single-use secret that is globally unique within the app during its lifetime. It responds to the terminal app's request:

```py
{"authorization_uri": "...",  # URL that user should visit in browser
 "verification_uri": "...",  # URL that terminal client will poll
 "interval": 5,  # suggested polling interval
 "session_id": "...",
 "expires_in": 60,  # seconds
 "user_code": "...", 
}
```

The terminal app prints the `user_code` and the `authorization_uri` (and maybe opens a browser tab using [`webbrowser.open()`](https://docs.python.org/3/library/webbrowser.html#webbrowser.open), where possible) and and then polls with this request:

```
POST {verification_uri}
{"session_id': <session_id>}
```

At first, the reply is:

```
400
{
  "error": "authorization_pending"
}
```

Meanwhile, the user navigates their browser to `authorization_url`, which is something like `https://example.org/...?response_type=code&client_id=...`&redirect_uri=.../api/auth/provider/<provider>/login. The user logs in, and is directed back to Tiled with `GET /api/auth/provider/<provider>/login?code=...

The `code` parameter is used by OAuth2 code flow in the usual way to confirm that the authorization is valid. On that page, the user is prompted to enter the `user_code` in a web form. The server than uses this to "activate" the session, updating its auth database accordingly.

The next time the terminal app polls, it gets a reply with refresh and access tokens. The auth database is updated to mark that the credentials have been collected. (If someone were to reply that request, it would be a error.) If the authorization does not complete before the `expires_in` time interval (~60 seconds) has passed, the client gives up and prints an error message. (If it were to persist past that deadline---again, an error.)

## Possible embellishment

To avoid the user even needing to enter that `user_code`, we could place it in the `state` query parameter of the `authorization_url`. It would then be passed back to like `GET /api/auth/provider/<provider>/login?code=...&state=<user_code>`. This reduces the user process to:

1. `c.login()`
2. Browser tab opens automatically (thanks to `webbrowser.open()`, where available) or user navigates to printed URL.
3. User authenticates and authorizes the Tiled application.
4. Terminal is now logged in.

...with no codes or tokens to enter or copy/paste. The downside here is that the `user_code` is "leaked" to the external authenticating entity. But I'm not sure that that is a concern.

Either way---whether or not the user has to enter a `user_code` in the browser manually---I think this is better UX than copy/pasting a giant refresh token from the browser into the Terminal app.

**Comment by dylanmcreynolds** [comment]
This is cool. I didn't realize this was an actual supported flow, but it makes sense, we we're seeing more and more applications perform this.

> Meanwhile, the user navigates their browser to authorization_url, which is something like https://example.org/...?response_type=code&client_id=...&redirect_uri=.../api/auth/provider//login. The user logs in, and is directed back to Tiled with `GET /api/auth/provider//login?code=...

Is there a reason not to make the reply for that initial request a redirect to the `authorization_url`, to reduce the clicks for the user?

**Comment by danielballan** [comment]
The initial request comes from the terminal, and we need to open `authorization_uri` is a browser, so redirect response won’t help. We can however use `webbrowser.open()` to navigate to that URL. (That is how Jupyter launches a browser tab when you start it in the command line.)

That will work from a terminal. But if the Python code is running within a notebook, we do not have access to open a new tab, so we will have to display a link as well for that scenario.

**Comment by dylanmcreynolds** [comment]
Something like this? (playing around with github's mermaid integration)

```mermaid
  sequenceDiagram
  actor user
  user ->> tiled_client: from_url()
  tiled_client ->> tiled_server:  POST /api/auth/<provider>/authorize
  activate tiled_server
    tiled_server->> db: write session row
    tiled_server -->> tiled_client: respond with session_id, expiration_time, user_code
  deactivate tiled_server
  alt browser available
     tiled_client ->> browser: open
  end

  loop every second
     tiled_client ->> tiled_server: is login complete?
     break  is activated
        tiled_client ->> user: message, you're logged in
     end
  end

  user ->> browser: navigate to authorization_url and authenticate with redirect url
  browser -->> user: redirect to tiled_server with user_code
  activate tiled_server
    browser ->> tiled_server: GET with user_code
    tiled_server ->> db: check user_code

  deactivate tiled_server
````

**Comment by danielballan** [comment]
Wow, awesome! I had a messy hand drawn version to explain this to myself. This is much better.

**Comment by clintonroy** [comment]
Just throwing a probably useless comment out there, i think how kubelogin does this cleanly is by spinning up a tiny local web server, just for the auth dance, connects to it with xdg-open, the page redirects to whatever auth source you've got, and then bounces back to a page on the local web server, which can that do whatever it likes with the auth code (in kubelogin's case, put it in the right place such that subsequent k8s commands can find it). I'm not 100% sure this poorly told tale helps.

**Comment by danielballan** [comment]
Oh, interesting! I had not considered this option.

I like that it avoids polling over the network: you just poll or watch a file (or something) instead.

Having given this all of ten minutes' thought, I think there is no way to make it work with a remote Jupyter server. That is, if I run this in a notebook and the notebook kernel is running on a cluster somewhere, there will be no way for me to connect to that tiny server. That can solved using Jupyter extensions that proxy the traffic (this is how dask dashboards work with Jupyter) but I don’t think we want to go there unless we have no alternative.

I wonder if this is how Globus works. I recall that their login process in slicker locally than on Jupyter. This might be why.

With "device code flow" the only difference between local use and remote Jupyter use is: locally we can use xdg-open to open a browser tab, and on Jupyter we will need the user to click a link.

So I think it is good to be aware of this approach, but that device code flow gives better, more consistent UX and has comparable complexity. (You can have poll over the network, but you do not need to start a small web server.) Does that sound right?

**Comment by danielballan** [comment]
Summarizing phone conversation with @dylanmcreynolds:

The API will support:
* normal code flow
* device code flow

Clients can use whichever makes sense for their application.

## Terminal-based interaction

The built-in Python client will use device code flow.

A new route `/api/auth/provider/<provider>/device_code` should be used as the `redirect_uri` for Terminal apps. When it receives this request, the server should perform the code exchange with the IdP (as `/code` does now) and activate the pending session in the auth database. When that is complete, it should return a redirect response, redirecting the user's browser to a static page that says "Success" and tells them to go back to their Terminal or whatever, which should shortly be receiving tokens from its polling loop. Or it can show a clear "Failure" message if something goes awry with the exchange.

## Web SPA interaction

The built-in React UI will use normal code flow. We will try to factor the React UI to encapsulate the JavaScript authentication code nicely (perhaps in a `<ContextProvider>`?) such can be easy reused in other apps. We may even be able to package it as an npm package that other React projects can just import.

Perhaps there is already a generalized package for authentication, but all the ones I could turn up were abandoned. This may be inherently coupled to the application just enough that it's hard to generalize in a way that really works. As @stuartcampbell has pointed out, the libraries available tend to be aligned with a particular authentication stack: There’s an okta library, auth0 library, AzureAD library, etc. If we were building Tiled just for NSLS2, that would clearly be the way to go. But, like Globus and like JupyterHub, we are chaining a Tiled authentication stack in front of a range of different external stacks. I think that's why we need our own thing.

The process will look like:
* In the SPA, the user clicks a "login" link and is navigated to the IdP. A `state` parameter i used to store a URL-encoded URL of where we left off in the SPA and want to return to after logging in. The `redirect_uri` points to a route in the SPA, not the Tiled API.
* After rediretion, the SPA pulls the `code` and the `state` from its query parameters.
* It requests `/api/auth/provider/<provider>/code?code=<code>`. The server does the code/token exchange and creates a session, exactly as it does in the current implementation. It should simply return the tokens as JSON.
* The SPA will stash the tokens in a `<ContextProvider>` or equivalent `localStorage` and use them for future requests.

**Comment by danielballan** [comment]
@clintonroy The GIF in this blog post shows one example of device code flow working from inside a Jupyter notebook: https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f

**Comment by danielballan** [comment]
Useful reference: https://github.com/jupyterhub/gh-scoped-creds/blob/main/gh_scoped_creds/__init__.py
