### ISSUE TITLE
Q:  How to query for only directories with python client?

### ISSUE THREAD

**Issue by pshafer-als** [bluesky/tiled#410]
I'm trying to use the built-in tiled client to search for directories, but ignore data files.  Server is using `DirectoryAdapter`.  I was expecting to be able to search for a Spec called "node", but queries along this line return no results.

Example:
```
  result = client.search(Spec("node"))
  print(f"{result = }")        # result = <Node {}>
  print(f"{len(result) = }")   # len(result) = 0

  print(f"{client.specs = }")                   # client.specs = ListView([])
  print(f"{list(client)[0] = }")                # list(client)[0] = '230210'
  print(f"{client[list(client)[0]].specs = }")  # client[list(client)[0]].specs = ListView([])
````

I feel like I'm missing something simple.  Do I need to define the directory spec myself in the config file for this root path?

Of course I can filter the results after I retrieve all contents of a node, but I'm hoping that doing this server-side is more performant (and already supported?).  I've hunted around in the code but not found anything yet.  Thanks for any suggestions!

**Comment by danielballan** [comment]
You want the [`StructureFamily` query](https://blueskyproject.io/tiled/reference/generated/tiled.queries.StructureFamily.html#tiled.queries.StructureFamily) which should do exactly what you want here.

A word on the distiction between "structure families" and "specs". Every object Tiled has exactly one `structure_family` (node, array, dataframe, or sparse). It _may_ additional have a list of `specs`, means to convey, "This is not just _any_ {node, array, dataframe, ...} but specifically one that meets certain expectations around shape, column names, and/or metadata keys, etc."

A client that understands the structure family should at least be able open and display the data. A client that _additionally_ understands one or more of the specs may be able to provide an "upgraded", more context-aware representation or interpretation of the data.

**Comment by pshafer-als** [comment]
> You want the [`StructureFamily` query](https://blueskyproject.io/tiled/reference/generated/tiled.queries.StructureFamily.html#tiled.queries.StructureFamily) which should do exactly what you want here.
> 
> A word on the distiction between "structure families" and "specs". Every object Tiled has exactly one `structure_family` (node, array, dataframe, or sparse). It _may_ additional have a list of `specs`, means to convey, "This is not just _any_ {node, array, dataframe, ...} but specifically one that meets certain expectations around shape, column names, and/or metadata keys, etc."
> 
> A client that understands the structure family should at least be able open and display the data. A client that _additionally_ understands one or more of the specs may be able to provide an "upgraded", more context-aware representation or interpretation of the data.

Thanks!  I'm not sure how I missed that.  `¯\_(ツ)_/¯`

On a related note will any of the query operators let me filter based on the _name_ or modification date of the node, or do I need to stash that info in the metadata for the node?

**Comment by danielballan** [comment]
Yes, there is `KeyLookup`. This one is on me: it's not documented with the others.

https://github.com/bluesky/tiled/blob/690e4d6cd5dd44230693095ff510517c5cb098df/tiled/queries.py#L64-L90

I think we are likely to promote `created_at` and `updated_at` and first-class concepts in Tiled, sitting _beside_ `metadata` along with `structure_family` and `specs` and give them special queries, just as we have queries `Specs` and `StructureFamily`. But we haven't done that yet, so for now you'd have to put that in `metadata` and use the normal general-purpose metadata queries.

**Comment by pshafer-als** [comment]
This is great.  Thank you!
