### ISSUE TITLE
Support Adapters that interact with authenticated services

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#453]
We have Tiled Adapters that interact with filesystems and databases. We have long planned Adapters that interact with services, but we have not yet implemented one.

To implement one, we seem to require two things:

1. The addition of "session state" to stash information that can be used to access the service. https://github.com/bluesky/tiled/blob/2862817d4e36e84ed8807344a95390712eb90cf3/tiled/database/orm.py#L184-L205
2. A way to pass session state to an Adapter

For (2) I propose this:

* Implement a new interface, which implements the method `with_session(session)` (name negotiable). That method should return an Adapter to an external service, and said Adapter should be passed the session info, including session state.
* In the server, [when we are traversing the URL path to find the entry of interest](https://github.com/bluesky/tiled/blob/2862817d4e36e84ed8807344a95390712eb90cf3/tiled/server/dependencies.py#L83), check for the method `with_session` and, if it's there, call it with the current session. This kind of thing is currently implement with `hasattr`, which is probably fine for now, but we should use protocols later: #449.

**Comment by dylanmcreynolds** [comment]
Just to be clear...for 1), you're proposing adding a column called `session_state`? Then maybe in the [Authenticator](https://github.com/bluesky/tiled/blob/2862817d4e36e84ed8807344a95390712eb90cf3/tiled/authenticators.py#L35) class, one could optionally add to the session row? This will also require that `Authenticator` also be enhanced to have some knowledge of the session?

**Comment by danielballan** [comment]
Currently, `Authenticator.authenticate(...)` returns the `username` as a string. What if it instead returned a model (could be `dataclass` or pydantic` or `namedtupe` or `dict`...) to make room for `username` and `session_state` and whatever else we might want later. This avoids coupling the Authenticators to the database but enables them to pass information to the database here:

https://github.com/bluesky/tiled/blob/2862817d4e36e84ed8807344a95390712eb90cf3/tiled/server/authentication.py#L663-L665

I remember, when drafting the Authenticators, think that I would eventually want a model with username _and_ (other stuff) but I kept it simple to start.

**Comment by dylanmcreynolds** [comment]
I like that.
