### ISSUE TITLE
Support FullText search in PostgreSQL

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#457]

**Comment by Kezzsim** [comment]
This is being developed on this branch of tiled:
https://github.com/Kezzsim/tiled/tree/smse_posgres
Under the tag *Scientific Metadata Search Engine* (**SMSE**) which includes fullText support items for Postgres, SQLite and the addition of typesense.

A PR will be added to this issue when ready, in the interim there are some resources I've been using to develop this support:
- [Video / Article on native Postgres text search using TSvector and TSquery](https://bigmachine.io/postgres/creating-a-full-text-search-engine-in-postgresql-2022/)
- [Notes on implementing full text search when using SQLAlchemy](https://amitosh.medium.com/full-text-search-fts-with-postgresql-and-sqlalchemy-edc436330a0c)
- [This SQLalchemy fullText search adaptor library on GitHub](https://github.com/liaden/sqlalchemy-pg-fts), we don't seem to need this *yet* and there may be supply chain concerns about bringing in a random library someone wrote.
