### ISSUE TITLE
SQLAlchemy Transactions

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#464]
I think that there are cases in the authentication code where we should wrap calls inside SQLAlchemy [transactions](https://docs.sqlalchemy.org/en/20/orm/session_transaction.html).  

Take for example: https://github.com/bluesky/tiled/blob/678cdede25f1d6920f47c64cad7f6ccc64a5ed64/tiled/server/authentication.py#L368

This method does the following with the database:

1. search for the user
2. search for the number of sessions the user has
3. if under the session limit, create a new session
4. search for the session again and return

Wrapping this in a transaction would assure that concurrent requests would not change the calculation of being done in step3. Also, if a failure happens in this method after the update in step3, then step3 would be rolled back. 

Finally, I believe that there's a performance benefit. Without a wrapping transaction, each database call incurs the cost of establishing its own transaction.

**Comment by danielballan** [comment]
I believe that a transaction is actually used here.

The variable `db` ultimately comes from this context manager

https://github.com/bluesky/tiled/blob/678cdede25f1d6920f47c64cad7f6ccc64a5ed64/tiled/database/connection_pool.py#L48-L51

which, if I understand correctly, opens a transaction, and automatically rolls it back upon exiting the context block unless the transaction is explicitly committed.

But this prompts two questions:

1. Am I right about that? We should run with SQLAlchemy's `echo` mode activated so we can see that actual SQL commands to confirm my understanding.
2. Relying on the caller to do the transaction seems sloppy, prone to misuse. Should we be using _nested_ transactions, a thing I have read about but never used, so this function runs a self-contained transaction and does not rely on the caller to get it right? At the very least we should add a code comment.

**Comment by dylanmcreynolds** [comment]
Oh, I see. I stand corrected. This is great.

I don't think we can prevent a caller from nesting transactions if they want...and that's fine. https://docs.sqlalchemy.org/en/20/orm/session_transaction.html#using-savepoint

I'll close this issue.
