### ISSUE TITLE
Enhancements to the directory tree

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#48]
- [x] By default, strip file extension from node name. That is, `a.tif` becomes `a`. Rationale: the file extension is not part of the "name". (Windows hides it by default.) Including it makes it confusing to do things like `http://.../thing.xlsx?format=csv`. This _does_ create the possibility of name collisions, but if you have `example.tiff` and `example.json` next to each other, they are likely related --- part of the same "data" --- and need a special Adapter to deal with. #49 
- [ ] Add a configurable function that, given a full path to a directory, returns a metadata dict. (The default will always return an empty dict.)
- [x] Add a configurable function that, given a full path to a directory, returns a mimetype or `None`. If it returns `None`, that means, "Crawl into this subdirectory." If it returns a mimetype, that means, "I recognize this as a {TIFF sequence, Zarr directory, TileDB directory} with internal structure than an Adapter shoudl manage. Do not crawl any further. We might want to make this a _list_ of functions to make it easy to extend default behavior. https://github.com/bluesky/tiled/pull/62

Developed in a phone conversation with @tacaswell

**Comment by J-avery32** [comment]
> Add a configurable function that, given a full path to a directory, returns a metadata dict.

Currently is there no way to add metadata for a node without re-writing the adapter to add this in?

**Comment by danielballan** [comment]
Correct. I think what you want here is similar to what we added in #259 — a way to _extend_ the existing behavior without having to rewrite a bunch of stuff.

**Comment by danielballan** [comment]
I think the feature you need is `subdirectory_handler`. Does each directory map to a single (3-dimensional) array, comprised off all the TIFFs stacked up, with a dictionary of metadata attached? If so, it should be fit your use case as is. See

https://github.com/bluesky/tiled/blob/34ede8a48bf3c9c901acc6ae7db3f12fbe2d0f2b/tiled/adapters/tiff.py#L178

and the (rough) documentation

https://blueskyproject.io/tiled/explanations/scaling-down.html

If the structure you need is more complex than that, we should talk about how to extend `subdirectory_handler` to enable it.

**Comment by danielballan** [comment]
@J-avery32 Does `subdirectory_handler` address your use case?

**Comment by J-avery32** [comment]
I'm not sure. How am I supposed to hook this up to read the json file in that directory? Or are you suggesting that I rewrite the Tiff adapter? Even if I re wrote the tiff adapter I don't see any way to give my new subdirectory_handler to tiled to use. Also I will be offline until Friday.

**Comment by J-avery32** [comment]
Ah! Never mind I think it does fit my use case. I will try it out and let you know.

**Comment by J-avery32** [comment]
How am I supposed to pass subdirectory_handler to tiled? Is there a hook in the yml for that or am I supposed to create a new DirectoryAdapter: https://blueskyproject.io/tiled/reference/generated/tiled.adapters.files.DirectoryAdapter.html?highlight=subdirectory_handler

**Comment by jmaruland** [comment]
You can create a config file that call a method which will load the right adapter.
trees:
```
  - tree: files
    path: /
    args:
      directory: files/
      subdirectory_handler: module:_subdirectory_handler_method
```

To run the config file with tiled you can use (https://blueskyproject.io/tiled/how-to/configuration.html):
`tiled serve config my_config_file.yml`

**Comment by J-avery32** [comment]
I need a little more time to think over this. I think it might be what I want. Originally I had each tiff file be its own separate node but hadn't considered joining it into a single 3 dimensional array. However, there are some csv files in these directories as well which are important. If I were to turn each directory into a 3 dimensional array then it seems that these csv files would disappear.

**Comment by danielballan** [comment]
@J-avery32 In #511 there are some changes that may be of interest:

1. The feature whereby Tiled automatically updates when the file system changes is now _opt in_. You need to add `--watch` to `tiled serve directory ...` to engage it.
2. The aforementioned `subdirectory_handler` is gone, in favor of an approach that is both easier to explain and more powerful. I think this is the way to handle "TIFF with associated JSON". Your use case may be a good way to test that and motivate a new documentation page to illustrate it. Can you expand a little on what your directories of files look like?

**Comment by J-avery32** [comment]
I'll get back to you on this, but it will take me a bit to go back through my old stuff and remember what I was trying to do.

**Comment by danielballan** [comment]
I'm going to close this now, as I think the use case of "node backed by heterogeneous files" is now addressed nicely.

Docs on how this works at a low level (in the database) are here: https://blueskyproject.io/tiled/explanations/catalog.html#data-source-asset-relation
