### ISSUE TITLE
docker not picking up TILED_CONFIG environment variable

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#494]
Somewhere between a76 and a98, something changed with how tiled picks up the `TILED_CONFIG` environment variable. In the newer version, it is ignored. We exec'd into the container and double checked that the variable is being set. Still, it appears to not be read in by tiled on startup.

As a workaround, we can add a command `tiled serve config /path/to/config.yml` and this works.

**Comment by danielballan** [comment]
The CI check using [container canary](https://github.com/NVIDIA/container-canary) failed to notice this because it specifically tests with the command `tiled serve catalog --temp`.
