### ISSUE TITLE
Change `metadata` from property to method.

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#515]
This has been on the table for awhile, and I think we have enough good reason to justify the change:

* It enables `metadata()` to be optionally async, as `read()` now is, if it needs to do blocking I/O.
* It leaves open a path to (optionally) accepting filter parameters for predicate push-down of something like JSONPath.

**Comment by danielballan** [comment]
Discussed on a call with @tacaswell. Agreed that a path to predicate push-down is important.

**Comment by padraic-shafer** [comment]
There seems to still be a mix of `metadata` sometimes as a "property" and sometimes as a "method".  This leads to e.g. being able to call either `read()` or `serialize_json()` on an xarray node(container) but not both.

I _think_ the update strategy from this PR simply need to be propagated elsewhere, but I haven't tested what might break if that happens.
* Remove `@property` from `def metadata(...`
* `X.metadata[...]` becomes `X.metadata()[...]`

See:
https://github.com/bluesky/tiled/blob/b3564569db8b80672a8e75583817e5b9f8e3a927/tiled/client/base.py#L157-L163
https://github.com/bluesky/tiled/blob/b3564569db8b80672a8e75583817e5b9f8e3a927/tiled/client/xarray.py#L99-L103

**Comment by padraic-shafer** [comment]
> I think the update strategy from this PR simply need to be propagated elsewhere, but I haven't tested what might break if that happens.

[UPDATE]  I tried this out locally and all tests pass.  Let me know if I should submit a PR for this.
