### ISSUE TITLE
Consider changing `id` to `key` in the HTTP API

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#516]
Using `id` is holdover from trying on JSON API. Now I worry it's confusing because:

* An `id` softly implies "unique" when in fact it's only unique within a given node in the logical tree.
* We use `keys()` in the Python API to match the `Mapping` interface, and so `item.key` would make sense.
* There is now a separate, internal unique `id` in the catalog database, which is not the `id` in the HTTP API.

While we are going through this round of backward-incompatible changes leading up to the v0.1.0 release, this is one to consider.

**Comment by dylanmcreynolds** [comment]
I'm not sold that this is worth breaking clients for.

**Comment by danielballan** [comment]
I think I agree. Of all the changes under consideration, this one is the most superficial. Unless someone chimes in to make the case, I will leave it alone.
