### ISSUE TITLE
Directory has empty specs

### ISSUE THREAD

**Issue by prjemian** [bluesky/tiled#535]
When serving a file directory (such as `tiled serve directory  --public --host 0.0.0.0 /tmp/examples/`), notice that the `specs` are empty.

```json
TILED
[Top](http://arf:8000/ui/browse/)
Detailed Machine-Readable Representation of Item
{
  "data": {
    "id": "",
    "attributes": {
      "ancestors": [],
      "structure_family": "node",
      "specs": [],
      "metadata": {},
      "structure": null,
      "sorting": [
        {
          "key": "_",
          "direction": 1
        }
      ],
      "references": null,
      "data_sources": null
    },
    "links": {
      "self": "http://arf:8000/api/v1/node/metadata/",
      "search": "http://arf:8000/api/v1/node/search/",
      "full": "http://arf:8000/api/v1/node/full/"
    },
    "meta": null
  },
  "error": null,
  "links": null,
  "meta": {}
}
```

Since there are specs for a `CatalogOfBlueskyRuns`, it seems natural for this to be a `Directory`.  A client that visits a server (providing multiple catalogs, some from directories, some from bluesky catalogs, some from something else) wants to know how to browse the structure for data content.

**Comment by danielballan** [comment]
What should a client do when it wants to know how to browse a given structure for data?

First, it should look at the `structure_family`. Every item in tiled always has exactly one of these, and it's from a fixed (not configurable list). This is enough information to know how to slice into it, know some of the formats it supports, and how to get from bytes to numbers.

Second, it should look for `specs`. This is a list, which may be empty. The specs are meant to be sorted from broadest to most precise, so you should keep going until you find one that you don't recognize. This provides additional context that may be useful in understanding the _meaning_ of data or metadata. For example, `CatalogOfBlueskyRuns` can be used to set the expectation that the contents have certain metadata like `start.time` and `start.scan_id`.

A generic directory or HDF5 group or any "container" does not have any specific attributes. Therefore I think it is well described by just the `structure_family`. I would layer on `specs` only if the directory or Group in question should be always expected to have specific metadata, or contain files/datasets with specific names.

**Comment by prjemian** [comment]
Thanks @danielballan, that answers my question!
