### ISSUE TITLE
Should we normalize the 'structure' column into its own table?

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#576]
The tiled catalog database stores the `structure` JSON in a column the `data_sources` table. If many `data_sources` share the same structure, that same information is stored many times. For `array` structures, which are fairly compact, the overhead is not so high. For `table` structures, which include base64-encoded Arrow schemas, the overhead can be significant. For `awkward` structures, they can be even more so.

Should we store `structure` in a separate table, reference by foreign key, perhaps using a hash of the JSON to uniquely key it? The benefit is more compact storage for repeated structures, which does seem like it could be large win for many/most use cases, where duplicate structures are common.

Adding another table does add more to the total complexity. I have a small reservation about making them one step more complicated to explain, inspect, to quickly understand. On the other hand, this change could actually make it _easier_ to look at and explain: with the noisy, not-so-human-readable structure off to the side, the `data_sources` table will be possible to fit on a screen and read.

This came up in https://github.com/jpivarski/tiled-uproot/discussions/1 with @jpivarski.

**Comment by danielballan** [comment]
I'd be interested in thoughts from @dylanmcreynolds and @padraic-shafer in particular here.

To illustrate the point, here's a Tiled catalog database that has one AwkwardArray in it. Recall we have:

- Nodes, the "logical" view
- Data Sources, which encode the structure and contain instructions that are used to find the appropriate Adapter and configure it
- Assets, which include files and/or directories that will be also be used to instantiate the Adapter

Relationships: Nodes have a one-to-many relation with Data Sources. Data Sources have a many-to-many relation with Assets. (Why many-to-many? One file may end up being used in many logical nodes. Example: calibration image.)

The `nodes` table and the `assets` table are quite readable and fairly self-describing.

```
sqlite> select * from nodes;
id  key   ancestors  structure_family  metadata  specs  time_created         time_updated       
--  ----  ---------  ----------------  --------  -----  -------------------  -------------------
1   test  []         awkward           {}        []     2023-10-06 20:35:03  2023-10-06 20:35:03

sqlite> select * from assets;
id  data_uri                                    is_directory  hash_type  hash_content  size  time_created         time_updated       
--  ------------------------------------------  ------------  ---------  ------------  ----  -------------------  -------------------
1   file://localhost/tmp/tmp8rybhsle/data/test  1                                            2023-10-06 20:35:03  2023-10-06 20:35:03
```

The `data_sources` table, with its fat `structure` column, is less so.

```
sqlite> select * from data_sources;
id  node_id  structure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         mimetype         parameters  management  time_created         time_updated       
--  -------  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  ---------------  ----------  ----------  -------------------  -------------------
1   1        {"length":3,"form":{"class":"ListOffsetArray","offsets":"i64","content":{"class":"RecordArray","fields":["x","y"],"contents":[{"class":"NumpyArray","primitive":"float64","inner_shape":[],"parameters":{},"form_key":"node2"},{"class":"ListOffsetArray","offsets":"i64","content":{"class":"NumpyArray","primitive":"int64","inner_shape":[],"parameters":{},"form_key":"node4"},"parameters":{},"form_key":"node3"}],"parameters":{},"form_key":"node1"},"parameters":{},"form_key":"node0"}}  application/zip  {}          writable    2023-10-06 20:35:03  2023-10-06 20:35:03
```

If we moved that to a separate table, that would leave something like:

```
sqlite> select node_id, mimetype, parameters, management, time_created, time_updated from data_sources;
node_id  mimetype         parameters  management  time_created         time_updated       
-------  ---------------  ----------  ----------  -------------------  -------------------
1        application/zip  {}          writable    2023-10-06 20:35:03  2023-10-06 20:35:03
```

...plus a new foreign key column. More complex, in that we have a new table, `structures`, and a new relation, Structures one-to-many with Data Sources. But maybe actually easier to digest? And the space savings from de-duplicating the structures may be too important to walk away from either way.

**Comment by danielballan** [comment]
(Aside: I see a bug there. That `mimetype` doesn't look right. We _transmit_ Awkward buffers as zip, but we store them as a raw binary buffers in files, so that should be `application/octet-stream`.)

**Comment by dylanmcreynolds** [comment]
So, if I understand correctly, the are a limited number of `structure` maps that are repeated a great many times, so this is a question of normalizing the schema?

I wouldn't worry too much about the added code complexity, rather the performance implications, since these tables are going to get hit a lot.

One common reason to normalize tables is to avoid updating many rows if the value changes, but I don't think structure will ever change.

The tradeoffs seem to me to be storage size vs adding table joins, which slow down queries. It's currently denormalized, and that's probably the fast query and the least efficient storage option. If you normalized it (putting it into it's own table), you would probably slow down queries but save space, right?

**Comment by padraic-shafer** [comment]
That was my reading of it also.  With SQL instead of Mongo joins are certainly more commonplace, right?  (At least I took some grief from @dylanmcreynolds when I initially used normalized schema in mongo for another project 😬)

My uneducated hunch is that for the table and awkward cases described above, having a separate DB table for the structure would be worthwhile tradeoff.  For the other datasets, they're probably small enough that the performance hit is not noticeable.

Key word in the previous paragraph is "uneducated".  Seems like a test with some real data is called for.

**Comment by danielballan** [comment]
Yes, these are good points. I may be overly focused on complexity, above; I just want to be sure this does not become too hard to explain.

We would definitely save space. The consequences for query speed may be subtle. If we make the data source table a lot lighter, that could have benefits that compensate for the extra join? Seems like something that we should measure.

**Comment by padraic-shafer** [comment]
I agree that the benefit of simplifying the `select * from data_sources;` query results far outweighs the tiny bump in telling new users that the structure is stored in a separate table. This is a win for the "teachable" axis of complexity.

**Comment by dylanmcreynolds** [comment]
Another thing...how canonical are these representations of structure? If we put them in a separate table could we end up dealing with many rows that are functional duplicates? That would be the worst of both worlds.

**Comment by danielballan** [comment]
Good question. The representations are canonical, up to the order of the keys. (Jim can say authoritatively for awkward, but I am pretty sure.)

If we key the structures on a hash of the JSON, we will need to be careful that the hash does not depend on key _order_; dask has the same issue when hashing a mapping. Straightforward, just something to keep in mind.

**Comment by dylanmcreynolds** [comment]
Ah hah! There's a spec that has a few python implementations.: https://www.rfc-editor.org/rfc/rfc8785

**Comment by danielballan** [comment]
Nice find!

**Comment by jpivarski** [comment]
Similarly for whitespace between tokens, though I suppose RFC-8785 standardizes that.

Would it help if `ak.forms.Form` instances had a `__hash__` method? Or is it already in a JSON format at this point in Tiled?

**Comment by danielballan** [comment]
Tiled carried it as a dict at this point, so I think we should probably work from the JSON.

**Comment by danielballan** [comment]
I'm thinking we should go ahead and make this change and evaluate performance as we go. The choice to start with de-normalized tables was fairly arbitrary, and I don't think the burden of proof to switch should be high at this early stage. We know right away that normalizing will give storage savings in a couple use cases we care about. Ifwe later find, through benchmarking and real-world usage, that the `JOIN` is dragging us down, we can look at a materialized view.
