### ISSUE TITLE
Add `POST` option for long `GET` URL queries

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#579]
In #577, we added `POST /awkward/buffers/{path}` as an alternative to `GET /awkward/buffers/{path}` that supports large number of buffers to be requested, placing the names of the buffers in the request body, as a JSON array, rather than in the URL query parameters.

The benefit of `POST` is that it scales; the benefit of `GET` is that HTTP response caches---be they web browser caches, the cache in Tiled's own Python client, or server-side caches---generally work on `GET` but not on `POST`.

We previously encountered the same problem with fetching wide xarray Datasets: we're selecting all the columns of scalar data, distinct from those with N-dimensional data, and it can be a large list. There, we took a different approach. Instead of adding a `POST` route, we split the `GET` request into multiple batches, with each `GET` fetching a subset of the keys.

https://github.com/bluesky/tiled/blob/1536fc3df93015c593270583cbb917afa3200fad/tiled/client/xarray.py#L144-L167

In the wild, we don't see _large_ number of batches needed...just a couple more than 1, sometimes.

I wonder if `POST` would be better here. The existing solution feels a bit fragile (hard-coded URL limit) and complex. For many use cases, Tiled's performance is latency-bound, and reducing the _number_ of requests has often been shown to be the best way to improve performance. Going from N `GET`s to one `POST` may be a win in this way.

We could potentially be benefiting from parallelism from the batched `GET`s, but as you can see we are not using parallelism here, just a simple loop. And we could do the same with batched `POST`, for that matter.

I cannot recall why we didn't go for `POST` from the start. I know I was aware of the pattern of using `POST` as an alt for `GET` when the requests parameters are large. Maybe I was highly weighting keeping HTTP response caching, because at the time we relied on it for Tiled's since-removed "offline mode".  As we now have a [more robust notion of how to achieve offline access](https://github.com/bluesky/tiled/issues/473), and it does not involve relying directly on an HTTP response cache, I think we should revisit this.

**Comment by padraic-shafer** [comment]
If we later get to the point where the loss of caching becomes an issue for these POST requests, there seems to be an accepted way to achieve that.

1. Client sends POST request; server responds with 200 OK response containing a [Content-Location header field that has the same value as the POST's effective request URI](https://stackoverflow.com/a/626083). Client could then use this new URI--a shortcut to the results of the POST query--in a cacheable GET query. Think _tinyurl_. The _Tiled_ python client could make this swap under the hood, without the user needing to know the details.

2. Alternatively it looks like the results of the POST request _could_ be directly cached, as long as there was [no mixing of POST/GET requests for the same URI](https://stackoverflow.com/a/828080). However, it also sounds like most web browsers do not handle this case, even when the server includes the necessary Cache-Control or Expires header fields in the response.

I think that we don't need to include that in this PR, but I'm noting it here as a future option.

**Comment by padraic-shafer** [comment]
I'd suggest that we use tests to drive the needed code updates for this.

E.g., Add a test to `test_xarray.py` that verifies a new (yet to be added) POST request--similar to what was done in #577 (_see below_) for reading awkward arrays. Then create the POST route that satisfies the test (without breaking other tests). Note that the important pieces of the test are (1) read xarray data without an error, and (2) verify that it occurred via a POST request.

https://github.com/bluesky/tiled/blob/a778e668bf5d12d80ee7145eb51d88486f6f88b2/tiled/_tests/test_awkward.py#L138-L142

I believe that we will want to repeat this for:
- [ ] test_array.py
- [ ] test_dataframe.py
- [ ] test_hdf5.py
- [ ] test_sparse.py
- [ ] test_structured_array.py
- [ ] test_tiff.py
- [ ] test_container_files.py

By that point, a POST route for `/container/full/{path}` has probably been created. If not, a container-specific test might be warranted--perhaps in `test_client.py` or `test_directory_walkers.py`.

**Comment by danielballan** [comment]
I agree that this task is a good fit for test-driven development.

The title for this issue suggests that we're adding `POST` routes for _all_ the structure families, but maybe we should step back and consider the problem we are trying to solve. We want to have an option for specifying requests when the parameters may become to large to fit into a URL. For /awkward/buffers/`, which prompted this line of thought, we take a list of buffers. There are realistic use cases where this list becomes very long.

We see the same issue with `/container/full`, `/table/full`, and `/table/partition`, which take a list of field or column names. For a "wide" container or table, this can be very long. We have seen in this in the wild with wide xarray.Datasets, which are represented in Tiled as a form of `container`. (As shown above, we currently use a workaround: multiple batches of `GET`.)

I am not sure that we will realistically have the same issue with `array` or `sparse` structures. They are parameterized by arguments like `?slice=10,100:1000,5:10`. Unless the array has ~100+ dimensions, we're not going to hit the URL limit with expressions like this any time soon. I think I would argue that keeping our API surface area lower outweighs any completionist argument for having `POST` on all the routes.

**Comment by padraic-shafer** [comment]
Thank you...this is helpful info!

As a first step, I'll rename the issue to better reflect a focus on these routes:  `/container/full`, `/table/full`, and `/table/partition`.

**Comment by padraic-shafer** [comment]
Restating several things here to solicit confirmation or correction...

1. Primary aim is to avoid super long URLs due to abundant query parameters.  Pass them in the body of POST request instead.
1. This has already been achieved for the `/awkward/...` routes by #577.
1. We still need to do this for `/container/full`, `/table/full`, and `/table/partition`. This is because they can contain many `field` or `column` parameters--e.g. from wide tables (many columns) or HDF5 files with many (possibly nested) fields.
1. We can ignore the "/array/..." routes because they are limited to a single `slice` query parameter, and even for multidimensional arrays that slice specifier is unlikely to reach 2000 characters.
1. Examples of Tables that we should test: pandas.DataFrame, xarray.Dataset; **others?**
1. Examples of Containers that we should test: file directory, Excel file, Zarr file, HDF5 file; **others?**
1. Specifically `ndarray` and `tiff (sequences)` are arrays and do NOT need to be considered here.  **Are there other notable cases to ignore?**

**Comment by padraic-shafer** [comment]
It probably makes sense to also update `/table/partition/{path}` to accept a `column` query parameter rather than `field`, as was recently done for `/table/full/{path}`.

Any objections?  Would it be preferable to make this a separate PR?

**Comment by padraic-shafer** [comment]
In the context of a file directory as `container`, would `field` correspond to the name of a file or subdirectory?  Or does it have some other meaning?

**Comment by danielballan** [comment]
Yes, all points true. Minor clarification on

> HDF5 files with many (possibly nested) fields

The contents may be nested, but the query can only filter the level-1 children of the node given in the path. You cannot pick out some level-2 children and exclude others. (This could be supported in the future but I am not sure it should be.)

Agreed about the field -> column rename. For back-compat, we should accept either, but for sanity we should raise if both are given.

Yes, it corresponds to the directory of filename. To be precise it typically corresponds to the filename excluding the extensions, so `a.csv` is just `a`. But this is configurable.

**Comment by danielballan** [comment]
I think you covered the important cases in Points 5–7.

I will expand on how xarray.Dataset works. It is a container, not a table. For one thing, there is no requirement that its "columns" (or as xarray calls them "variables") be the same length. It cannot in general be represented cleanly in a tabular format. So, should we download each variable individually as an array? We learned the hard way that it is deeply inefficient to download a wide xarray with a separate`/array/block` request for each of the N variables. To optimize, we request `/container/full` for those variables that are scalar and of equal length and conceptually could fit into a CSV. (We use Arrow, though.) Then, for the remaining variables, we request chunks via `/array/block`. For a given variable, we may use one request or multiple depending on the size of the data.

**Comment by padraic-shafer** [comment]
> Agreed about the field -> column rename. For back-compat, we should accept either, but for sanity we should raise if both are given.

We should be able to do something like the following, then handle the logic inside the route's endpoint handler.  We could update both `/table/full/{path}` and `/table/partition/{path}` this way.

```python3
    column: Optional[List[str]] = Query(None, min_length=1),
    field: Optional[List[str]] = Query(None, min_length=1, deprecated=True),
```

**Comment by DiamondJoseph** [comment]
@danielballan https://www.rfc-editor.org/info/rfc10008/ move support to QUERY for 2.0?
