### ISSUE TITLE
Support single-user API key configuration via CLI arg?

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#583]
In a development or demo context, it is convenient to start a writable server with a stable single-user API key, such that restarting the server does not require copying a new key over into the client. As such, I type this a lot:

```
TILED_SINGLE_USER_API_KEY=secret tiled catalog serve --temp
```

It might be nicer to type something like

```
tiled catalog serve --temp --api-key=secret
```

## Considerations on whether we should add this at all

I intentionally avoided doing this at first because I worry that it makes it too easy to run a server with an insecure (guessable) API key. But, the `TILED_SINGLE_USER_API_KEY=secret ...` pattern is now all over the docs, so it's not exactly hard to discover, and I think there may not be much value in making it inconvenient to set.

## Considerations on what to name it.

Maybe it should be `--token` instead of `--api-key`? I think `token`:

* May be more memorable to non-devs
* Is easy to _say_ (as opposed to "A P I dash...no, dash, not underscore...KEY") which comes up in a my life...
* Matches what Jupyter uses, for what it's worth

In fact I wonder if everywhere we have `api_key`...

* `$ tiled api_key ...`
* `https://...?api_key=...`

we should instead name it `token`. I chose `api_key` early on because at the time I wasn't sure if "token" had a certain precise technical meaning. Now, years into this, it seems to me that "token" is used broadly to cover both API keys (e.g. GitHub "Personal Access Token") and the more transient bearer tokens used in OAuth2.

Early on, I also wondered if we'd run into confusing name collisions between API key-style tokens and OAuth2 tokens. But, as the latter are managed internally and transparently to the user, this potential name collision does not really end up being user-facing.

Thoughts?

**Comment by vshekar** [comment]
This sounds pretty reasonable to me. 

Is there a possibility of the tiled server needing other tokens/secrets to start up? In which case a `--token-file` and pass in a `secrets.json` file or reuse `--token` to detect either a token passed into the command or a json file. I personally like my secrets to be in a separate file :smile:

**Comment by danielballan** [comment]
Good question. At that point, you escalate to `tiled serve config config.yml`, which in turn can reference env vars, which might come from `.env` etc.

**Comment by danielballan** [comment]
...though really, even in the simple use case with just one `--token`, having a `--token-file` option may be a nice option to provide.

**Comment by dylanmcreynolds** [comment]
I like moving it out of the env variable and into the CLI. I don't have a strong opinion about api_key vs token. api_keys. Doing some general reading, api_keys let you identify an application rather than a user. I still kind of think they're useful for that.

**Comment by danielballan** [comment]
For sure. We need API keys; I just wasn't sure about the name.

I'll leave the name alone. It's probably getting to the point where we'd be breaking too many users. The term "API key" is all through the code base, so this would be a large and tricky change.
