### ISSUE TITLE
Clean up extraneous print() statements

### ISSUE THREAD

**Issue by padraic-shafer** [bluesky/tiled#589]
Some tests have stray `print()` statements that might have been left over from local debugging sessions?

I'll gladly submit a PR, but will first post some clarification questions below.  It would be helpful to receive feedback before proceeding.

**Comment by padraic-shafer** [comment]
zipfile module has a lot of `print()` statements.  Could these be moved to logging?

**Comment by padraic-shafer** [comment]
> zipfile module has a lot of `print()` statements. Could these be moved to logging?

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L1412

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L1425C13-L1425C19

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L1440C17-L1440C23

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L1498C17-L1498C23

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L1509-L1514

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2106C13-L2108C23

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2119-L2123

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2139-L2140

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2143-L2144

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2149-L2150

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2155-L2156

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2159-L2160

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2166-L2167

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2181-L2187

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/_zipfile_py39.py#L2558-L2560

**Comment by padraic-shafer** [comment]
## Tests

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/scripts/json_indexes.py#L33

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/_tests/test_array.py#L111-L112

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/_tests/test_hdf5.py#L35

**Comment by padraic-shafer** [comment]
## Not tests

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/authenticators.py#L289-L295

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/adapters/tiff.py#L147

**Comment by padraic-shafer** [comment]
Could/should this one move to a logger?

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/_tests/conftest.py#L86-L89

**Comment by danielballan** [comment]
Thanks for this pass through the codebase. Quick comments for context:

`_zipfile_py39` is a copy of the `zipfile` module from CPython itself, as of version 3.9. I think it's best to leave "vendored" code as is rather than diverge. Context is here:

https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/serialization/awkward.py#L9-L15

I'm inclined to leave this one alone, just a dev-oriented script where logging feels too heavy.

[tiled/scripts/json_indexes.py](https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/scripts/json_indexes.py#L33)

This is also vendored code (from the JupyterHub SAML authenticator) so I'd tend toward leaving it.

[tiled/tiled/authenticators.py](https://github.com/bluesky/tiled/blob/7c122f9307b52c24cfba4c3b7e23d2ebe720a694/tiled/authenticators.py#L289-L295)

The rest can be deleted or converting to logging as you wish!

**Comment by padraic-shafer** [comment]
Thanks for providing this context.  I'll go with your suggestions.  

I was cleaning up some temporary changes on my fork and thought that I might as well do some thorough housekeeping. :)
