### ISSUE TITLE
Logout should revoke user's session?

### ISSUE THREAD

**Issue by padraic-shafer** [bluesky/tiled#602]
The `/logout` route currently clears the cookie that stores the API key.  It seems like this call should also [revoke the current session](https://github.com/bluesky/tiled/blob/4ef171605f28bc3503db9f8ed39cf7b889e68379/tiled/server/authentication.py#L897-L904) to prevent further use of the associated tokens.  Does that sound reasonable?

https://github.com/bluesky/tiled/blob/4ef171605f28bc3503db9f8ed39cf7b889e68379/tiled/server/authentication.py#L1098-L1106

**Comment by danielballan** [comment]
Yes. The logout code paths in general need review before we tag beta.
