### ISSUE TITLE
Writing data to empty data dir

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#625]
Should adapters like this, that write data, sending `parent=True` so that necessary subdirectories where data is written to are created?
https://github.com/bluesky/tiled/blob/d3c94fad814166759f57c3bba47c65601f25e1f9/tiled/adapters/parquet.py#L45
On a new tiled install, we couldn't write parquet files until several subdirectories were manually created.

**Comment by danielballan** [comment]
This might have been a manifestation of https://github.com/bluesky/tiled/pull/626, if you were using `create_container`.

Using `parent=True` can mask bugs: the data will definitely get _written_ but may not where we expected.... If we can, I'd like to insist that directories get created explicitly exactly when they are needed. If there are usability issues (like creating the root directory at server startup) let's address them.

**Comment by danielballan** [comment]
I've changed my view on this. Let's create parent directories on demand. This is similar to how directories are handled in `git`: not explicitly tracked as independent entities in the data model, but created as needed.

**Comment by danielballan** [comment]
Action here:

- [ ] Cherry-pick 51dbe383246ee6280e142155f81d7f6043c50139 from #626 (the unit test).
- [ ] Use `parents=True` in all the `tiled.adapters.*` that support `write`.
- [ ] Add more examples to the test (e.g. for sparse and awkward). Maybe parameterize it.
