### ISSUE TITLE
orjson required for (writing from?) client, but isn't in client dependencies

### ISSUE THREAD

**Issue by pbeaucage** [bluesky/tiled#636]
A Tiled client, when writing to a server using `write_array`, uses `orjson` to serialize the metadata, which I believe was a change introduced at some point.  However, `orjson` is only a dependency in `server` and `minimal-server` which means it isn't installed when doing `pip install tiled[client]` and the client hits an import error during write which is not ideal.

**Comment by danielballan** [comment]
Good catch! Thanks for reporting.

**Comment by danielballan** [comment]
Closed by #639
