### ISSUE TITLE
Should we rename the `FullText` query to just `Text`?

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#643]
I think `FullText` is both verbose and a bit technical; maybe just plain `Text` would be better.

I also anticipate adding `FuzzyText` in the near future, with @Kezzsim's TypeSense work, and we wouldn't want `FuzzyFullText`....

**Comment by padraic-shafer** [comment]
...or maybe `Search` and `FuzzySearch` are both simple and well understood?

**Comment by danielballan** [comment]
You make a decent point about `FullText`. I worry about `Search` being _too_ generic, as illustrated by the usage:

```py
c.search(Search(...))
```

**Comment by danielballan** [comment]
Closing this as a bad idea. :-D
