### ISSUE TITLE
Healthchecks and containers

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/tiled#648]
Without other configuration, container systems determine that tiled is healthy by waiting on the entrypoint/command to exit. If you're using docker-compose or k8s, you probably want to be more specific.  Your probably want to send http requests to the server instead. 

For k8s, I think you can configure this within the manifest by configuring what url to [fetch from](https://www.paulsblog.dev/how-to-successfully-implement-a-healthcheck-in-docker-compose/).  For docker-compose, I think you need to configure a script to run in the container. The simplest example I can think see is in the [docker-compose](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck) documentation.

So, I have two ideas in this area for tiled to consider:

1. Incur the massive overhead of installing `curl` in the tiled docker image so make this easier.
2. Add a `healthz` endpoint to the tiled server so that when we see these health requests, we know why, and we can code it to do as little work as we can get away with.

**Comment by danielballan** [comment]
I would merge PRs doing both.
