### ISSUE TITLE
Tiled client ``from_context`` keeps adding specs until pydantic validation fails 

### ISSUE THREAD

**Issue by canismarko** [bluesky/tiled#651]
I'm trying to use the ``from_context`` function to create a local tiled server for use in writing tests.

After creating the client a number of times, it suddenly starts failing with pydantic Validation errors saying there are more than 20 spec objects. Here is the tail end of the exception.

```
File /local/mambaforge/envs/haven/lib/python3.10/site-packages/tiled/server/core.py:492, in construct_resource(base_url, path_parts, entry, fields, select_metadata, omit_links, show_sources, media_type, max_depth, depth)
    485         else:
    486             attributes["sorting"] = [
    487                 {"key": key, "direction": direction}
    488                 for key, direction in entry.sorting
    489             ]
    490 d = {
    491     "id": path_parts[-1] if path_parts else "",
--> 492     "attributes": schemas.NodeAttributes(**attributes),
    493 }
    494 if not omit_links:
    495     d["links"] = {
    496         "self": f"{base_url}/metadata/{path_str}",
    497         "search": f"{base_url}/search/{path_str}",
    498         "full": f"{base_url}/container/full/{path_str}",
    499     }

File /local/mambaforge/envs/haven/lib/python3.10/site-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for NodeAttributes
specs
  ensure this value has at most 20 items (type=value_error.list.max_items; limit_value=20)
```

Here is a minimum working example: https://gist.github.com/canismarko/8d5a1a1850dffa7e532de05449383fac

With some breakpoints, it looks like ``entry.specs`` keeps getting longer, adding a new ``Spec("xarray_data")`` (or something like that) each time.

This also happens if I create the client once, and then just read the data multiple times, i.e. move everything but ``data.read()`` outside that for loop.

It does not happen if I use a normal ``from_uri(...)`` client and access a running tiled server.

**Comment by danielballan** [comment]
Thanks for the report and the very nice reproducible example @canismarko. I have proposed a fix in https://github.com/bluesky/tiled/pull/653. Against that PR branch, your example runs.

**Comment by canismarko** [comment]
My pleasure. Thanks for getting the fix done.
