### ISSUE TITLE
Server secret key rotation

### ISSUE THREAD

**Issue by gwbischof** [bluesky/tiled#7]
Add secret key rotation to the server.

**Comment by danielballan** [comment]
Support was added in #4 

https://github.com/bluesky/tiled/pull/4/files#diff-36f2c40eaa91b23bcf212df0678297538c5fc50ba76439af00016b7409656dcdR14-R17

https://github.com/bluesky/tiled/pull/4/files#diff-36f2c40eaa91b23bcf212df0678297538c5fc50ba76439af00016b7409656dcdR76

https://github.com/bluesky/tiled/pull/4/files#diff-36f2c40eaa91b23bcf212df0678297538c5fc50ba76439af00016b7409656dcdR88-R100
