### ISSUE TITLE
Support chunked responses

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#70]
Currently, the media type serialization registry contains _functions_. It should also accept _generator functions_ that yield the data in chunks. This may reduce the server's memory usage, and it will enable us to start servicing a request faster.

1. Teach this codepath that it might receives bytes (current behavior) or a generator instance (new behavior). https://github.com/bluesky/tiled/blob/70a8e1b687c27a52c37ee7aabaaf6da5d2bfc248/tiled/server/core.py#L425
   We can check whether the return value is a generator using `isinstance(content, types.GeneratorType)`. If it's a generator, return a `PatchedStreamingResponse` instead of a `PatchedResponse`. https://github.com/bluesky/tiled/blob/70a8e1b687c27a52c37ee7aabaaf6da5d2bfc248/tiled/server/core.py#L437-L441
2. Convert some of the existing serializers to generator functions. This may be done by taking the existing functions like `serialize_csv` and building generators that wrap them, as illustrated in my comment below. Then, the function version becomes an internal utility and the generator version takes its place in the registry here: https://github.com/bluesky/tiled/blob/70a8e1b687c27a52c37ee7aabaaf6da5d2bfc248/tiled/structures/array.py#L177-L178

**Comment by danielballan** [comment]
For example, this is the standard CSV serializer, currently in `tiled.structures.array`:

```py
def serialize_csv(array, metadata):
    # (metadata is not used in this case, but it's part of the the tiled server's expected signature for serializers)
    file = io.StringIO()
    numpy.savetxt(file, array, fmt="%s", delimiter=",")
    return file.getvalue().encode()
```

and here is a sketch of a streaming CSV serializer.

```py
def serialize_csv_chunked(array, metadata):
    assert array.ndim == 2
    # Serialize up to N bytes at a time.
    N = 10_000_000  # 10 MB
    items_per_chunk = N / array.itemsize
    items_per_row = array.shape[1]
    rows_per_chunk = items_per_chunk // item_per_row
    for offset in range(0, array.shape[0], rows_per_chunk):
        chunk = array[offset:offset + rows_per_chunk]
        yield serialize_csv(chunk, metadata)
```

**Comment by SimonHeybrock** [comment]
Would this approach serve well for data that may not be fully available, but gets updated periodically?

```python
def serialize_continuous(array, metadata):
    while True:
        yield serialize_array(array, metadata)

# elsewhere (driven by Kafka stream):
array.data += new_data
```

**Comment by danielballan** [comment]
@SimonHeybrock and I discussed this via a private channel. For anyone who runs across this later, see the result of that conversation in #85.
