### ISSUE TITLE
`client` requirements should include `starlette`

### ISSUE THREAD

**Issue by pbeaucage** [bluesky/tiled#711]
#694 and #650 added `starlette` status constants to the client, but `starlette` never made it into the client requirements causing an import error if you only install `tiled[client]`.

I believe it should be in both [client] and [minimal-client].

A broader question as this has happened before: could we add a CI test that installs the package with just `[minimal-client]` or `[client]` and verifies (to first order) that the package imports, and ideally that a basic client function test passes, maybe against the public test server?  This would likely have to be its own GHA/non-`pytest` script since afaik there is no environment control at the `pytest` level.

**Comment by danielballan** [comment]
Good call @pbeaucage! :+1: for a test with `client` and `minimal-client` deps only.
