### ISSUE TITLE
Numpy 2.0.0 breaks Tiled

### ISSUE THREAD

**Issue by hyperrealist** [bluesky/tiled#757]
In the recent [scheduled CI runs](https://github.com/bluesky/tiled/actions/runs/9541880111) Numpy 2.0.0 breaks Tiled. As a temporary measure, PR #756 pins to Numpy <2.0.0, but Tiled should be fully migrated to support Numpy 2.0.0. We also have a dependency on blosc2 that seems to depend on Numpy ABI.

Here is the migration guide: https://numpy.org/devdocs/numpy_2_0_migration_guide.html

**Comment by danielballan** [comment]
Oh good catch! We've been doing this for other projects; it was a miss not to think of addressing this in advance of the release.

I think only a few changes are needed for compatibility; see #758.
