### ISSUE TITLE
Allow for automatically clearing default identity on logout

### ISSUE THREAD

**Issue by jwlodek** [bluesky/tiled#790]
As seen at beamlines that are moving to tiled currently, if the user does `tiled_reading_client.logout()`, upon next startup, the `Username` field in the auth prompt will be automatically set to that user, without the ability to go back and change it. Adding `username=None` to the `from_profile` solves that, but then you are prompted for re-login every restart of bsui.

What I would expect is that when I explicitly logout from the client, there should be an option to clear the default identity for setups like this. At the same time, I think default behavior can stay as it is, since for dev setups having username be remembered is nice.

I already started a PR for this, but wanted to document in an issue first before submitting.

**Comment by danielballan** [comment]
Thanks for documenting this issue. A fix is overdue.

With #791 I wonder about creeping configuration bloat. Would it be sufficient to change the login prompt to something like this?

```
Username [dallan]:
```

where pressing Enter accepts the default identity, but users can type an alternative?

**Comment by jwlodek** [comment]
I think thats a reasonable solution. Does remove an extra kwarg that needs to be passed around everywhere which is nice.

**Comment by danielballan** [comment]
We could additionally add a keyword argument to logout, like `logout(clear=True)` as a convenience alias for `logout(); clear_default_identity()`

**Comment by jwlodek** [comment]
That was my first idea as well, and I think it would be a good option to allow as well.
