### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#8]
I think we will need to support all of the following. Users can escalate depending on the level of customization and complexity they need.

1. CLI args
2. Environment variables
3. `.env` file
4. Statically analyzable config (either JSON, YAML, INI, or TOML)
5. Direct modification of the app in Python

## Breakdown

1. CLI args

This is useful for simple deployment and just getting started. It might look like:

```
tiled serve ... --authenticator="package.module:AuthenticatorClass" --allow-anonymous-access --secret-keys="..."
```

2. Environment variables

This is useful for injecting configuration into containers, which is expected to be a common deployment scenario.

```
TILED_AUTHENICATOR=""package.module:AuthenticatorClass" TILED_ALLOW_ANONYMOU_ACCESS=1 TILED_SECRET_KEYS="..." tiled serve ... 
```

3. Dot env file

A simple and common variation on (2)

```
# ./.env
TILED_AUTHENICATOR=""package.module:AuthenticatorClass"
TILED_ALLOW_ANONYMOU_ACCESS=1
TILED_SECRET_KEYS="..."
```

```
tiled serve ...
```

4.Statically analyzable config

This is useful when the catalog-specific configuration is nontrivial and when multiple catalogs are served by a single server at different routes.

I am leaning toward [TOML](http://toml.io/) format, which might look roughly like this. (See further below for comparison of TOML, JSON, YAML, and INI foirmats in the context of Tiled.)

```toml
[/raw]
class = "databroker.drivers.mongo_normalized"
args = []
kwargs.metadatastore_uri = "mongodb://..."
kwargs.handler_registry = {"AD_HDF5": "..."}

[/processed]
class = "databroker.drivers.mongo_normalized"
args = []
kwargs.metadatastore_uri = "${MONGO_URI}"  # Our parser would layer regex-based env var replacement onto TOML.
kwargs.handler_registry = {"AD_HDF5": "..."}
```

5. Directly modify app in Python

This requires more knowledge of the app's internals than (4) but may be simpler and more direct than using config is some cases. This is the "break glass if..." scenario, where you want to do deep customization.

## Comparison of TOML, JSON, YAML, INI

This is not a _general_ comparison, but rather a comparison specifically in the context of the needs of Tiled.

###  JSON

Pro:
* The Python standard library has a built-in parser.
* It's a well-known format.

Con:
* It does not support comments. Configuration files really need comments, so I view this as a deal-breaker.

### YAML

Pro:
* It is widely used for configuration in the worlds of Docker and Kubernetes.
* It is what we have used in Databroker and intake.

Con:
* It is _too_ flexible for the job, and it performs heuristic parsing that is well known to lead to very confusing bugs.
* Its parsers are relatively heavy dependencies for what we actually need.

### INI

Pro:
* Very common and familiar.
* The Python standard library has a built-in parser.

Con:
* It only supports strings, so any other types (numbers, dates) have to be inferred.
* There is no formal spec; when parsers have varied behavior there is no way to decide which one is "right".

### [TOML](https://toml.io/en/v1.0.0)

Pro:
* Designed specifically as a configuration file format, as opposed to a generic data format.
* Feels/looks similar to INI, but formally specified.
* Supports comments.
* Less flexible than YAML, in a good way.
* Much lighter dependency than YAML parsers.
* Parsers exists in many languages.

Con:
* Less mainstream than YAML or JSON, and yet another format to learn, although it is used already by Python for new-style packaging (`pyproject.toml`)
* Adds a dependency (unlike JSON)
* Means we’d have to deal with both YAML and TOML during the transition from intake and Databroker v0.

I think TOML and YAML are the strong contenders here. My approach with Tiled so far has been to pick the best tool for the job and not be shy about adopting new technologies (see also: FastAPI) so I lean TOML, but I think it's worth considering the trade-offs for a moment before we commit.

Another thought: We could always support either if we really want! As precedent, Ansible and IPython/Jupyter both support more than one format. The structure is what matters, not the encoding.

**Comment by dylanmcreynolds** [comment]
This is a good overview. Would python be configured in a standard file name or a configured file? With python available, than I think the choice of ini/json/yaml/toml is less significant. Someone could write their own configuration format if they had a toml allergy.

I've never worked with toml, but I like it the idea.

For the file-based configuration, would endpoints be served by the same workers (same process), or separate invocations of uvicorn? Whatever we come up with, I feel like both cases should be supported. There are some times where for simplicity I'd just have them all in on process, other times that I'd want to separate them in case one is prone to starve the others.

Just thinking about deployment, I have found that the easiest way to deploy fastapi apps is with the tiangolo/uvicorn-gunicorn-fastapi docker image. This easiest way to use the above would be with environment variables, which I think means each endpoint would have its own container (with a N worker process, as configured in gunicorn). If I wanted to take advantage of a configuration file, I could mount a volume to that file...maybe that could be a default known location with a commandline/env variable that could override that? Would it be directory of files  or individual file? I think I prefer individual files for simplicity.

**Comment by danielballan** [comment]
> Would python be configured in a standard file name or a configured file? 

I neglected to mention that I think the config path should be explicit. A config file would be invoked like:

```
tiled serve config <path/to/config_file.whatever>
```

> With python available, than I think the choice of ini/json/yaml/toml is less significant. Someone could write their own configuration format if they had a toml allergy.

Agreed. As a thought-provoking comment (not a practical suggestion) you can always use FUSE to rewrite one as the other, as long as you have Python! The choice is not so important.

> Whatever we come up with, I feel like both cases should be supported. 

Good point. Agreed.

>  If I wanted to take advantage of a configuration file, I could mount a volume to that file...maybe that could be a default known location with a commandline/env variable that could override that?

I vote for starting with an explicit commandline / env variable and potentially adding a search path later.

> Would it be directory of files or individual file? I think I prefer individual files for simplicity.

I'm of two minds about this. From the perspective of packaging an deployment, separate files is better than multiple agents editing one file. (Jupyter transitioned from single-file config to `*.d/`-style config for this reason a couple years ago.) OTOH, I agree that a single file make simple cases easier. An example of this would be `~/.config/kube`.

**Comment by danielballan** [comment]
Upon reflection...

Given how prolific YAML is in both ops and data science (GitHub actions, k8s, dask, intake, old databroker) I think I need to let go of my attachment to TOML. I have made YAML the "default" but JSON files are also accepted and TOML is accepted too, as long as you have `toml` installed. We won't require `toml`, only `pyyaml`. And of course `json` comes standard.

**Comment by danielballan** [comment]
Another point against TOML here is that the thing people like the _least_ about its formatting is [the way it spells an array of tables](https://toml.io/en/v1.0.0#array-of-tables)  (i.e. list-of-dicts in Python). It is the least intuitive aspect of the format, and it the part that we would need.
