### ISSUE TITLE
Make authentication prompt hookable

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#815]
How we can able GUIs to use the Tiled Python client and authenticate with HTTP basic auth into OAuth2? Currently, Tiled prompts for a username and password using TTY input.

These lines

https://github.com/bluesky/tiled/blob/2459624dcf53e87e94299b439cf10b1d009f4e0a/tiled/client/context.py#L558-L559

can be factored into a global function:

```py
def prompt_for_credentials(username=None) -> (username, password):
     "Accept optional default username, return username and password."
    ...
```

The `Context.__init__` can grow an optional argument, default `None` that enables overriding this function. The constructor functions `from_uri` and `from_profile` can grow the same argument and pass it through.

We should also consider what might be needed to support login via a browser, where Tiled is providing a URL and polling (device code flow) for the user to complete login and authorization. This does not need to be solved in the same PR, but we have a sense of what the interface will be so that the API proposed above is consistent with that.

**Comment by maffettone** [comment]
A possibility is to just modify the `authenticate` method and not the `Context` object. 
```python

  def prompt_for_credentials(username, password):
        if username and password:
            # Only keep u+p if both provided. In the rare case that someone provides a pwd and not username, reprompt.
            return username and password
        elif username:
            username_reprompt = input(f"Username [{username}]: ")
            if len(username_reprompt.strip()) != 0:
                username = username_reprompt
        else:
            username = input("Username: ")
        password = getpass.getpass()
        return username, password
        

  def authenticate(
      self,
      username=UNSET,
      provider=UNSET,
      prompt_for_reauthentication=UNSET,
      set_default=True,
      *
      password=UNSET, # Add password here, and tuck behind *
  ):
  ...
     if mode == "password":
          username, password = prompt_for_credentials(username, password)
          form_data = {
              "grant_type": "password",
              "username": username,
              "password": password,
          }
          token_response = self.http_client.post(
              auth_endpoint, data=form_data, auth=None
          )
          handle_error(token_response)
          tokens = token_response.json()
    ...
```

**Comment by danielballan** [comment]
I like this. Much simpler than what I proposed, and I can't think of any downsides. If the session expires or is revoked, we want to make sure that this won't prompt for reauthentication. (See that parameter, `prompt_for_reauthentication`). I think that if it's False that will raise an exception that the GUI could catch, but that should be checked and tested.
