### ISSUE TITLE
Add prometheus metrics

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#83]
Draw inspiration from https://docs.dask.org/en/latest/setup/prometheus.html. Exposing `gc` metrics in particular seems a good idea.

**Comment by dylanmcreynolds** [comment]
I love this.

**Comment by dylanmcreynolds** [comment]
What about also exposing time spent processing requests?

**Comment by danielballan** [comment]
Might also be use to count socket and file system reads.

**Comment by danielballan** [comment]
I wonder if it’s appropriate to use Python audit hooks for that kind of performance tracing.

**Comment by danielballan** [comment]
We needed to start capturing metrics urgently to make sense of some user reports, so I rushed something into `main`. Needs docs and refinement.

**Comment by danielballan** [comment]
The socket and file usage can be observed through a generic node_exporter. I don’t think we need the Tiled application to do anything special there.

Still needs docs.

**Comment by danielballan** [comment]
Old gist that is relevant: https://gist.github.com/danielballan/1bfb0576781c5671e3b97af2ebafcfa1

**Comment by danielballan** [comment]
Evidently `podman-compose` does not support `--scale`. It seems to silently ignore it, as reported here: https://github.com/containers/podman-compose/issues/267
